sudo: required
language: go
go:

services:
  - docker

before_install:
  - docker-compose up --build

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "go-project"
  env: "Goproject-env"
  bucket_name: "elasticbeanstalk-eu-west-2-071338906295"
  bucket_path: "go-project"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"